### PR TITLE
Code style fixes and cleanup of console output

### PR DESCRIPTION
**Pull request by deckchairlabs**
This PR removes some console output and also cleans up commented out code, version control is here for a reason :)

### CODE REVIEW

**Comment by dbox** [comment]
@arccoza any word on this? I'm having the extra console output as well

image @trajedy

**Comment by deckchairlabs** [comment]
@dbox yes would like to get this merged, just a little bit too much noise on the console for my liking. @arccoza any chance of getting this merged?

**Comment by arccoza** [comment]
Some tidy-up is coming.

**Review by arccoza — COMMENTED** [review]
I'm going to merge this, including the style changes, except the white-space between functions and args, I really don't like that style; for future reference.

**Comment by dbox** [comment]
thnx @arccoza and @trajedy !

**Comment by arccoza** [comment]
Alright guys, tidy-up published to NPM.

**Comment by dbox** [comment]
🙇

**Comment by dbox** [comment]
I got the greenlight to add this to [rucksack](https://github.com/simplaio/rucksack), so doing that soon.

**Comment by arccoza** [comment]
Great stuff.

**Pull request merged**
